### ISSUE TITLE
添加到 HanLP 的衍生项目

### ISSUE THREAD

**Issue by boliza** [shikeio/elasticsearch-analysis-hanlp#1]
@hankcs

本项目为一个 ES plugin，从 ES 6.0.0 开始 ，与 ES 同步更新。

还请添加到 衍生项目里面

**Comment by hankcs** [comment]
感谢开源工作，已经添加到https://github.com/hankcs/HanLP/wiki/%E8%A1%8D%E7%94%9F%E9%A1%B9%E7%9B%AE

**Comment by boliza** [comment]
Thanks
